# Generated by Django 5.0.3 on 2024-04-04 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allegro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CLIENT_ID', models.CharField(max_length=255, null=True)),
                ('CLIENT_SECRET', models.CharField(max_length=999, null=True)),
                ('access_token', models.CharField(max_length=999, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.allegro')),
            ],
        ),
    ]
