# Generated by Django 5.0.3 on 2024-04-05 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_allegro_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='refresh_token',
            field=models.CharField(max_length=999, null=True),
        ),
    ]
