# Generated by Django 5.0.3 on 2024-04-23 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_secret_dpd_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secret',
            name='access_token',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='secret',
            name='dpd_access_token',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='secret',
            name='refresh_token',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
