# Generated by Django 5.0.3 on 2024-05-24 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_secret_access_token_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=125, null=True)),
                ('lastName', models.CharField(max_length=125, null=True)),
                ('company', models.CharField(max_length=125, null=True)),
                ('street', models.CharField(max_length=125, null=True)),
                ('streetNumber', models.CharField(max_length=125, null=True)),
                ('postalCode', models.CharField(max_length=125, null=True)),
                ('city', models.CharField(max_length=125, null=True)),
                ('email', models.CharField(max_length=125, null=True)),
                ('phone', models.CharField(max_length=125, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
