services:

  db:
    image: postgres:latest
    container_name: postgres_sellior
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  web:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: sellior_backend
    command: sh -c "uvicorn api_app.asgi:application --reload --host 0.0.0.0 --port 8000"
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env

volumes:
  postgres_data:
