services:

  db:
    image: postgres:15
    container_name: postgres_sellior
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGPORT: ${DB_PORT}
    ports:
      - "5434:5434"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - db-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  web:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: sellior_backend
    command: sh -c "uvicorn api_app.asgi:application --host 0.0.0.0 --port 8004 --workers 2"
    restart: always
    volumes:
      - .:/app
      # - static_volume:/app/staticfiles
    networks:
      - db-net
      - web-net 
    ports:
      - "8004:8004"
    expose:
      - "8004"
    env_file:
      - .env
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8004",]
    #   start_period: 300s
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5



#  nginx:
 #   build: ./nginx
  #  container_name: sellior_nginx
   # volumes:
    #  - static_volume:/app/staticfiles
     # - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    #networks:
    # - web-net
    #ports:
    #  - "81:80"  # Maps port 80 on your VPS to port 80 in the nginx container
    #depends_on:
    #  web:
    #    condition: service_healthy

volumes:
  postgres_data:
  # static_volume:
networks:
  db-net:
  web-net:
